version: "3.0"

services:
  web:
    build: ./server
    volumes:
      - ./server:/usr/src/server
    ports:
      - 5000:5000
    depends_on:
      - elasticsearch
  tools:
    build: ./tools
    volumes:
      - ./tools:/usr/src/tools
    depends_on:
      - elasticsearch
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.7.0
    environment:
      - discovery.type=single-node
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
    volumes:
      - es-data:/usr/share/elasticsearch/data
  kibana:
    image: docker.elastic.co/kibana/kibana:7.7.0
    ports:
      - 5601:5601
volumes:
  es-data:
    driver: local